// AUTOGENERATED FILE. DO NOT EDIT

//go:build js

package rl

// Quaternion, 4 components (Vector4 alias)
type Quaternion = Vector4

// Texture2D, same as Texture
type Texture2D = Texture

// TextureCubemap, same as Texture
type TextureCubemap = Texture

// RenderTexture2D, same as RenderTexture
type RenderTexture2D = RenderTexture

// Camera type fallback, defaults to Camera3D
type Camera = Camera3D
