// AUTOGENERATED FILE. DO NOT EDIT

//go:build js

package rl

const RaylibVersionMajor = 5

const RaylibVersionMinor = 6

const RaylibVersionPatch = 0

const RaylibVersion = "5.6-dev"

const Pi = 3.14159265358979323846

const Deg2Rad = (Pi / 180.0)

const Rad2Deg = (180.0 / Pi)

// Light Gray
var Lightgray = Color{200, 200, 200, 255}

// Gray
var Gray = Color{130, 130, 130, 255}

// Dark Gray
var Darkgray = Color{80, 80, 80, 255}

// Yellow
var Yellow = Color{253, 249, 0, 255}

// Gold
var Gold = Color{255, 203, 0, 255}

// Orange
var Orange = Color{255, 161, 0, 255}

// Pink
var Pink = Color{255, 109, 194, 255}

// Red
var Red = Color{230, 41, 55, 255}

// Maroon
var Maroon = Color{190, 33, 55, 255}

// Green
var Green = Color{0, 228, 48, 255}

// Lime
var Lime = Color{0, 158, 47, 255}

// Dark Green
var DarkGreen = Color{0, 117, 44, 255}

// Sky Blue
var Skyblue = Color{102, 191, 255, 255}

// Blue
var Blue = Color{0, 121, 241, 255}

// Dark Blue
var Darkblue = Color{0, 82, 172, 255}

// Purple
var Purple = Color{200, 122, 255, 255}

// Violet
var Violet = Color{135, 60, 190, 255}

// Dark Purple
var Darkpurple = Color{112, 31, 126, 255}

// Beige
var Beige = Color{211, 176, 131, 255}

// Brown
var Brown = Color{127, 106, 79, 255}

// Dark Brown
var Darkbrown = Color{76, 63, 47, 255}

// White
var White = Color{255, 255, 255, 255}

// Black
var Black = Color{0, 0, 0, 255}

// Blank (Transparent)
var Blank = Color{0, 0, 0, 0}

// Magenta
var Magenta = Color{255, 0, 255, 255}

// My own White (raylib logo)
var Raywhite = Color{245, 245, 245, 255}

const MouseLeftButton = MouseButtonLeft

const MouseRightButton = MouseButtonRight

const MouseMiddleButton = MouseButtonMiddle

const MaterialMapDiffuse = MaterialMapAlbedo

const MaterialMapSpecular = MaterialMapMetalness

const ShaderLocMapDiffuse = ShaderLocMapAlbedo

const ShaderLocMapSpecular = ShaderLocMapMetalness

// Compatibility hack for previous raylib versions
var GetMouseRay = GetScreenToWorldRay
