// AUTOGENERATED FILE. DO NOT EDIT

//go:build js

package rl

//go:wasmimport _raylib _InitWindow
//go:noescape
func initWindow(
	Width int32,
	Height int32,
	Title cptr,
)

//go:wasmimport _raylib _CloseWindow
//go:noescape
func closeWindow()

//go:wasmimport _raylib _WindowShouldClose
//go:noescape
func windowShouldClose(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowReady
//go:noescape
func isWindowReady(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowFullscreen
//go:noescape
func isWindowFullscreen(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowHidden
//go:noescape
func isWindowHidden(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowMinimized
//go:noescape
func isWindowMinimized(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowMaximized
//go:noescape
func isWindowMaximized(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowFocused
//go:noescape
func isWindowFocused(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowResized
//go:noescape
func isWindowResized(
	ret cptr,
)

//go:wasmimport _raylib _IsWindowState
//go:noescape
func isWindowState(
	ret cptr,
	Flag uint32,
)

//go:wasmimport _raylib _SetWindowState
//go:noescape
func setWindowState(
	Flags uint32,
)

//go:wasmimport _raylib _ClearWindowState
//go:noescape
func clearWindowState(
	Flags uint32,
)

//go:wasmimport _raylib _ToggleFullscreen
//go:noescape
func toggleFullscreen()

//go:wasmimport _raylib _ToggleBorderlessWindowed
//go:noescape
func toggleBorderlessWindowed()

//go:wasmimport _raylib _MaximizeWindow
//go:noescape
func maximizeWindow()

//go:wasmimport _raylib _MinimizeWindow
//go:noescape
func minimizeWindow()

//go:wasmimport _raylib _RestoreWindow
//go:noescape
func restoreWindow()

//go:wasmimport _raylib _SetWindowIcon
//go:noescape
func setWindowIcon(
	Image cptr,
)

//go:wasmimport _raylib _SetWindowIcons
//go:noescape
func setWindowIcons(
	Images cptr,
	Count int32,
)

//go:wasmimport _raylib _SetWindowTitle
//go:noescape
func setWindowTitle(
	Title cptr,
)

//go:wasmimport _raylib _SetWindowPosition
//go:noescape
func setWindowPosition(
	X int32,
	Y int32,
)

//go:wasmimport _raylib _SetWindowMonitor
//go:noescape
func setWindowMonitor(
	Monitor int32,
)

//go:wasmimport _raylib _SetWindowMinSize
//go:noescape
func setWindowMinSize(
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _SetWindowMaxSize
//go:noescape
func setWindowMaxSize(
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _SetWindowSize
//go:noescape
func setWindowSize(
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _SetWindowOpacity
//go:noescape
func setWindowOpacity(
	Opacity float32,
)

//go:wasmimport _raylib _SetWindowFocused
//go:noescape
func setWindowFocused()

//go:wasmimport _raylib _GetWindowHandle
//go:noescape
func getWindowHandle(
	ret cptr,
)

//go:wasmimport _raylib _GetScreenWidth
//go:noescape
func getScreenWidth(
	ret int32,
)

//go:wasmimport _raylib _GetScreenHeight
//go:noescape
func getScreenHeight(
	ret int32,
)

//go:wasmimport _raylib _GetRenderWidth
//go:noescape
func getRenderWidth(
	ret int32,
)

//go:wasmimport _raylib _GetRenderHeight
//go:noescape
func getRenderHeight(
	ret int32,
)

//go:wasmimport _raylib _GetMonitorCount
//go:noescape
func getMonitorCount(
	ret int32,
)

//go:wasmimport _raylib _GetCurrentMonitor
//go:noescape
func getCurrentMonitor(
	ret int32,
)

//go:wasmimport _raylib _GetMonitorPosition
//go:noescape
func getMonitorPosition(
	ret cptr,
	Monitor int32,
)

//go:wasmimport _raylib _GetMonitorWidth
//go:noescape
func getMonitorWidth(
	ret int32,
	Monitor int32,
)

//go:wasmimport _raylib _GetMonitorHeight
//go:noescape
func getMonitorHeight(
	ret int32,
	Monitor int32,
)

//go:wasmimport _raylib _GetMonitorPhysicalWidth
//go:noescape
func getMonitorPhysicalWidth(
	ret int32,
	Monitor int32,
)

//go:wasmimport _raylib _GetMonitorPhysicalHeight
//go:noescape
func getMonitorPhysicalHeight(
	ret int32,
	Monitor int32,
)

//go:wasmimport _raylib _GetMonitorRefreshRate
//go:noescape
func getMonitorRefreshRate(
	ret int32,
	Monitor int32,
)

//go:wasmimport _raylib _GetWindowPosition
//go:noescape
func getWindowPosition(
	ret cptr,
)

//go:wasmimport _raylib _GetWindowScaleDPI
//go:noescape
func getWindowScaleDPI(
	ret cptr,
)

//go:wasmimport _raylib _GetMonitorName
//go:noescape
func getMonitorName(
	ret cptr,
	Monitor int32,
)

//go:wasmimport _raylib _SetClipboardText
//go:noescape
func setClipboardText(
	Text cptr,
)

//go:wasmimport _raylib _GetClipboardText
//go:noescape
func getClipboardText(
	ret cptr,
)

//go:wasmimport _raylib _GetClipboardImage
//go:noescape
func getClipboardImage(
	ret cptr,
)

//go:wasmimport _raylib _EnableEventWaiting
//go:noescape
func enableEventWaiting()

//go:wasmimport _raylib _DisableEventWaiting
//go:noescape
func disableEventWaiting()

//go:wasmimport _raylib _ShowCursor
//go:noescape
func showCursor()

//go:wasmimport _raylib _HideCursor
//go:noescape
func hideCursor()

//go:wasmimport _raylib _IsCursorHidden
//go:noescape
func isCursorHidden(
	ret cptr,
)

//go:wasmimport _raylib _EnableCursor
//go:noescape
func enableCursor()

//go:wasmimport _raylib _DisableCursor
//go:noescape
func disableCursor()

//go:wasmimport _raylib _IsCursorOnScreen
//go:noescape
func isCursorOnScreen(
	ret cptr,
)

//go:wasmimport _raylib _ClearBackground
//go:noescape
func clearBackground(
	Color cptr,
)

//go:wasmimport _raylib _BeginDrawing
//go:noescape
func beginDrawing()

//go:wasmimport _raylib _EndDrawing
//go:noescape
func endDrawing()

//go:wasmimport _raylib _BeginMode2D
//go:noescape
func beginMode2D(
	Camera cptr,
)

//go:wasmimport _raylib _EndMode2D
//go:noescape
func endMode2D()

//go:wasmimport _raylib _BeginMode3D
//go:noescape
func beginMode3D(
	Camera cptr,
)

//go:wasmimport _raylib _EndMode3D
//go:noescape
func endMode3D()

//go:wasmimport _raylib _BeginTextureMode
//go:noescape
func beginTextureMode(
	Target cptr,
)

//go:wasmimport _raylib _EndTextureMode
//go:noescape
func endTextureMode()

//go:wasmimport _raylib _BeginShaderMode
//go:noescape
func beginShaderMode(
	Shader cptr,
)

//go:wasmimport _raylib _EndShaderMode
//go:noescape
func endShaderMode()

//go:wasmimport _raylib _BeginBlendMode
//go:noescape
func beginBlendMode(
	Mode int32,
)

//go:wasmimport _raylib _EndBlendMode
//go:noescape
func endBlendMode()

//go:wasmimport _raylib _BeginScissorMode
//go:noescape
func beginScissorMode(
	X int32,
	Y int32,
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _EndScissorMode
//go:noescape
func endScissorMode()

//go:wasmimport _raylib _BeginVrStereoMode
//go:noescape
func beginVrStereoMode(
	Config cptr,
)

//go:wasmimport _raylib _EndVrStereoMode
//go:noescape
func endVrStereoMode()

//go:wasmimport _raylib _LoadVrStereoConfig
//go:noescape
func loadVrStereoConfig(
	ret cptr,
	Device cptr,
)

//go:wasmimport _raylib _UnloadVrStereoConfig
//go:noescape
func unloadVrStereoConfig(
	Config cptr,
)

//go:wasmimport _raylib _LoadShader
//go:noescape
func loadShader(
	ret cptr,
	VsFileName cptr,
	FsFileName cptr,
)

//go:wasmimport _raylib _LoadShaderFromMemory
//go:noescape
func loadShaderFromMemory(
	ret cptr,
	VsCode cptr,
	FsCode cptr,
)

//go:wasmimport _raylib _IsShaderValid
//go:noescape
func isShaderValid(
	ret cptr,
	Shader cptr,
)

//go:wasmimport _raylib _GetShaderLocation
//go:noescape
func getShaderLocation(
	ret int32,
	Shader cptr,
	UniformName cptr,
)

//go:wasmimport _raylib _GetShaderLocationAttrib
//go:noescape
func getShaderLocationAttrib(
	ret int32,
	Shader cptr,
	AttribName cptr,
)

//go:wasmimport _raylib _SetShaderValue
//go:noescape
func setShaderValue(
	Shader cptr,
	LocIndex int32,
	Value cptr,
	UniformType int32,
)

//go:wasmimport _raylib _SetShaderValueV
//go:noescape
func setShaderValueV(
	Shader cptr,
	LocIndex int32,
	Value cptr,
	UniformType int32,
	Count int32,
)

//go:wasmimport _raylib _SetShaderValueMatrix
//go:noescape
func setShaderValueMatrix(
	Shader cptr,
	LocIndex int32,
	Mat cptr,
)

//go:wasmimport _raylib _SetShaderValueTexture
//go:noescape
func setShaderValueTexture(
	Shader cptr,
	LocIndex int32,
	Texture cptr,
)

//go:wasmimport _raylib _UnloadShader
//go:noescape
func unloadShader(
	Shader cptr,
)

//go:wasmimport _raylib _GetScreenToWorldRay
//go:noescape
func getScreenToWorldRay(
	ret cptr,
	Position cptr,
	Camera cptr,
)

//go:wasmimport _raylib _GetScreenToWorldRayEx
//go:noescape
func getScreenToWorldRayEx(
	ret cptr,
	Position cptr,
	Camera cptr,
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _GetWorldToScreen
//go:noescape
func getWorldToScreen(
	ret cptr,
	Position cptr,
	Camera cptr,
)

//go:wasmimport _raylib _GetWorldToScreenEx
//go:noescape
func getWorldToScreenEx(
	ret cptr,
	Position cptr,
	Camera cptr,
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _GetWorldToScreen2D
//go:noescape
func getWorldToScreen2D(
	ret cptr,
	Position cptr,
	Camera cptr,
)

//go:wasmimport _raylib _GetScreenToWorld2D
//go:noescape
func getScreenToWorld2D(
	ret cptr,
	Position cptr,
	Camera cptr,
)

//go:wasmimport _raylib _GetCameraMatrix
//go:noescape
func getCameraMatrix(
	ret cptr,
	Camera cptr,
)

//go:wasmimport _raylib _GetCameraMatrix2D
//go:noescape
func getCameraMatrix2D(
	ret cptr,
	Camera cptr,
)

//go:wasmimport _raylib _SetTargetFPS
//go:noescape
func setTargetFPS(
	Fps int32,
)

//go:wasmimport _raylib _GetFrameTime
//go:noescape
func getFrameTime(
	ret float32,
)

//go:wasmimport _raylib _GetTime
//go:noescape
func getTime(
	ret float64,
)

//go:wasmimport _raylib _GetFPS
//go:noescape
func getFPS(
	ret int32,
)

//go:wasmimport _raylib _SwapScreenBuffer
//go:noescape
func swapScreenBuffer()

//go:wasmimport _raylib _PollInputEvents
//go:noescape
func pollInputEvents()

//go:wasmimport _raylib _WaitTime
//go:noescape
func waitTime(
	Seconds float64,
)

//go:wasmimport _raylib _SetRandomSeed
//go:noescape
func setRandomSeed(
	Seed uint32,
)

//go:wasmimport _raylib _GetRandomValue
//go:noescape
func getRandomValue(
	ret int32,
	Min int32,
	Max int32,
)

//go:wasmimport _raylib _LoadRandomSequence
//go:noescape
func loadRandomSequence(
	ret cptr,
	Count uint32,
	Min int32,
	Max int32,
)

//go:wasmimport _raylib _UnloadRandomSequence
//go:noescape
func unloadRandomSequence(
	Sequence cptr,
)

//go:wasmimport _raylib _TakeScreenshot
//go:noescape
func takeScreenshot(
	FileName cptr,
)

//go:wasmimport _raylib _SetConfigFlags
//go:noescape
func setConfigFlags(
	Flags uint32,
)

//go:wasmimport _raylib _OpenURL
//go:noescape
func openURL(
	Url cptr,
)

//go:wasmimport _raylib _SetTraceLogLevel
//go:noescape
func setTraceLogLevel(
	LogLevel int32,
)

//go:wasmimport _raylib _TraceLog
//go:noescape
func traceLog(
	LogLevel int32,
	Text cptr,
	Args cptr,
)

//go:wasmimport _raylib _SetTraceLogCallback
//go:noescape
func setTraceLogCallback(
	Callback cptr,
)

//go:wasmimport _raylib _MemAlloc
//go:noescape
func memAlloc(
	ret cptr,
	Size uint32,
)

//go:wasmimport _raylib _MemRealloc
//go:noescape
func memRealloc(
	ret cptr,
	Ptr cptr,
	Size uint32,
)

//go:wasmimport _raylib _MemFree
//go:noescape
func memFree(
	Ptr cptr,
)

//go:wasmimport _raylib _LoadFileData
//go:noescape
func loadFileData(
	ret cptr,
	FileName cptr,
	DataSize cptr,
)

//go:wasmimport _raylib _UnloadFileData
//go:noescape
func unloadFileData(
	Data cptr,
)

//go:wasmimport _raylib _SaveFileData
//go:noescape
func saveFileData(
	ret cptr,
	FileName cptr,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _ExportDataAsCode
//go:noescape
func exportDataAsCode(
	ret cptr,
	Data cptr,
	DataSize int32,
	FileName cptr,
)

//go:wasmimport _raylib _LoadFileText
//go:noescape
func loadFileText(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _UnloadFileText
//go:noescape
func unloadFileText(
	Text cptr,
)

//go:wasmimport _raylib _SaveFileText
//go:noescape
func saveFileText(
	ret cptr,
	FileName cptr,
	Text cptr,
)

//go:wasmimport _raylib _SetLoadFileDataCallback
//go:noescape
func setLoadFileDataCallback(
	Callback cptr,
)

//go:wasmimport _raylib _SetSaveFileDataCallback
//go:noescape
func setSaveFileDataCallback(
	Callback cptr,
)

//go:wasmimport _raylib _SetLoadFileTextCallback
//go:noescape
func setLoadFileTextCallback(
	Callback cptr,
)

//go:wasmimport _raylib _SetSaveFileTextCallback
//go:noescape
func setSaveFileTextCallback(
	Callback cptr,
)

//go:wasmimport _raylib _FileRename
//go:noescape
func fileRename(
	ret int32,
	FileName cptr,
	FileRename cptr,
)

//go:wasmimport _raylib _FileRemove
//go:noescape
func fileRemove(
	ret int32,
	FileName cptr,
)

//go:wasmimport _raylib _FileCopy
//go:noescape
func fileCopy(
	ret int32,
	SrcPath cptr,
	DstPath cptr,
)

//go:wasmimport _raylib _FileMove
//go:noescape
func fileMove(
	ret int32,
	SrcPath cptr,
	DstPath cptr,
)

//go:wasmimport _raylib _FileTextReplace
//go:noescape
func fileTextReplace(
	ret int32,
	FileName cptr,
	Search cptr,
	Replacement cptr,
)

//go:wasmimport _raylib _FileTextFindIndex
//go:noescape
func fileTextFindIndex(
	ret int32,
	FileName cptr,
	Search cptr,
)

//go:wasmimport _raylib _FileExists
//go:noescape
func fileExists(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _DirectoryExists
//go:noescape
func directoryExists(
	ret cptr,
	DirPath cptr,
)

//go:wasmimport _raylib _IsFileExtension
//go:noescape
func isFileExtension(
	ret cptr,
	FileName cptr,
	Ext cptr,
)

//go:wasmimport _raylib _GetFileLength
//go:noescape
func getFileLength(
	ret int32,
	FileName cptr,
)

//go:wasmimport _raylib _GetFileModTime
//go:noescape
func getFileModTime(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _GetFileExtension
//go:noescape
func getFileExtension(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _GetFileName
//go:noescape
func getFileName(
	ret cptr,
	FilePath cptr,
)

//go:wasmimport _raylib _GetFileNameWithoutExt
//go:noescape
func getFileNameWithoutExt(
	ret cptr,
	FilePath cptr,
)

//go:wasmimport _raylib _GetDirectoryPath
//go:noescape
func getDirectoryPath(
	ret cptr,
	FilePath cptr,
)

//go:wasmimport _raylib _GetPrevDirectoryPath
//go:noescape
func getPrevDirectoryPath(
	ret cptr,
	DirPath cptr,
)

//go:wasmimport _raylib _GetWorkingDirectory
//go:noescape
func getWorkingDirectory(
	ret cptr,
)

//go:wasmimport _raylib _GetApplicationDirectory
//go:noescape
func getApplicationDirectory(
	ret cptr,
)

//go:wasmimport _raylib _MakeDirectory
//go:noescape
func makeDirectory(
	ret int32,
	DirPath cptr,
)

//go:wasmimport _raylib _ChangeDirectory
//go:noescape
func changeDirectory(
	ret cptr,
	DirPath cptr,
)

//go:wasmimport _raylib _IsPathFile
//go:noescape
func isPathFile(
	ret cptr,
	Path cptr,
)

//go:wasmimport _raylib _IsFileNameValid
//go:noescape
func isFileNameValid(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadDirectoryFiles
//go:noescape
func loadDirectoryFiles(
	ret cptr,
	DirPath cptr,
)

//go:wasmimport _raylib _LoadDirectoryFilesEx
//go:noescape
func loadDirectoryFilesEx(
	ret cptr,
	BasePath cptr,
	Filter cptr,
	ScanSubdirs cptr,
)

//go:wasmimport _raylib _UnloadDirectoryFiles
//go:noescape
func unloadDirectoryFiles(
	Files cptr,
)

//go:wasmimport _raylib _IsFileDropped
//go:noescape
func isFileDropped(
	ret cptr,
)

//go:wasmimport _raylib _LoadDroppedFiles
//go:noescape
func loadDroppedFiles(
	ret cptr,
)

//go:wasmimport _raylib _UnloadDroppedFiles
//go:noescape
func unloadDroppedFiles(
	Files cptr,
)

//go:wasmimport _raylib _GetDirectoryFileCount
//go:noescape
func getDirectoryFileCount(
	ret uint32,
	DirPath cptr,
)

//go:wasmimport _raylib _GetDirectoryFileCountEx
//go:noescape
func getDirectoryFileCountEx(
	ret uint32,
	BasePath cptr,
	Filter cptr,
	ScanSubdirs cptr,
)

//go:wasmimport _raylib _CompressData
//go:noescape
func compressData(
	ret cptr,
	Data cptr,
	DataSize int32,
	CompDataSize cptr,
)

//go:wasmimport _raylib _DecompressData
//go:noescape
func decompressData(
	ret cptr,
	CompData cptr,
	CompDataSize int32,
	DataSize cptr,
)

//go:wasmimport _raylib _EncodeDataBase64
//go:noescape
func encodeDataBase64(
	ret cptr,
	Data cptr,
	DataSize int32,
	OutputSize cptr,
)

//go:wasmimport _raylib _DecodeDataBase64
//go:noescape
func decodeDataBase64(
	ret cptr,
	Text cptr,
	OutputSize cptr,
)

//go:wasmimport _raylib _ComputeCRC32
//go:noescape
func computeCRC32(
	ret uint32,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _ComputeMD5
//go:noescape
func computeMD5(
	ret cptr,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _ComputeSHA1
//go:noescape
func computeSHA1(
	ret cptr,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _ComputeSHA256
//go:noescape
func computeSHA256(
	ret cptr,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _LoadAutomationEventList
//go:noescape
func loadAutomationEventList(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _UnloadAutomationEventList
//go:noescape
func unloadAutomationEventList(
	List cptr,
)

//go:wasmimport _raylib _ExportAutomationEventList
//go:noescape
func exportAutomationEventList(
	ret cptr,
	List cptr,
	FileName cptr,
)

//go:wasmimport _raylib _SetAutomationEventList
//go:noescape
func setAutomationEventList(
	List cptr,
)

//go:wasmimport _raylib _SetAutomationEventBaseFrame
//go:noescape
func setAutomationEventBaseFrame(
	Frame int32,
)

//go:wasmimport _raylib _StartAutomationEventRecording
//go:noescape
func startAutomationEventRecording()

//go:wasmimport _raylib _StopAutomationEventRecording
//go:noescape
func stopAutomationEventRecording()

//go:wasmimport _raylib _PlayAutomationEvent
//go:noescape
func playAutomationEvent(
	Event cptr,
)

//go:wasmimport _raylib _IsKeyPressed
//go:noescape
func isKeyPressed(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _IsKeyPressedRepeat
//go:noescape
func isKeyPressedRepeat(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _IsKeyDown
//go:noescape
func isKeyDown(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _IsKeyReleased
//go:noescape
func isKeyReleased(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _IsKeyUp
//go:noescape
func isKeyUp(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _GetKeyPressed
//go:noescape
func getKeyPressed(
	ret int32,
)

//go:wasmimport _raylib _GetCharPressed
//go:noescape
func getCharPressed(
	ret int32,
)

//go:wasmimport _raylib _GetKeyName
//go:noescape
func getKeyName(
	ret cptr,
	Key int32,
)

//go:wasmimport _raylib _SetExitKey
//go:noescape
func setExitKey(
	Key int32,
)

//go:wasmimport _raylib _IsGamepadAvailable
//go:noescape
func isGamepadAvailable(
	ret cptr,
	Gamepad int32,
)

//go:wasmimport _raylib _GetGamepadName
//go:noescape
func getGamepadName(
	ret cptr,
	Gamepad int32,
)

//go:wasmimport _raylib _IsGamepadButtonPressed
//go:noescape
func isGamepadButtonPressed(
	ret cptr,
	Gamepad int32,
	Button int32,
)

//go:wasmimport _raylib _IsGamepadButtonDown
//go:noescape
func isGamepadButtonDown(
	ret cptr,
	Gamepad int32,
	Button int32,
)

//go:wasmimport _raylib _IsGamepadButtonReleased
//go:noescape
func isGamepadButtonReleased(
	ret cptr,
	Gamepad int32,
	Button int32,
)

//go:wasmimport _raylib _IsGamepadButtonUp
//go:noescape
func isGamepadButtonUp(
	ret cptr,
	Gamepad int32,
	Button int32,
)

//go:wasmimport _raylib _GetGamepadButtonPressed
//go:noescape
func getGamepadButtonPressed(
	ret int32,
)

//go:wasmimport _raylib _GetGamepadAxisCount
//go:noescape
func getGamepadAxisCount(
	ret int32,
	Gamepad int32,
)

//go:wasmimport _raylib _GetGamepadAxisMovement
//go:noescape
func getGamepadAxisMovement(
	ret float32,
	Gamepad int32,
	Axis int32,
)

//go:wasmimport _raylib _SetGamepadMappings
//go:noescape
func setGamepadMappings(
	ret int32,
	Mappings cptr,
)

//go:wasmimport _raylib _SetGamepadVibration
//go:noescape
func setGamepadVibration(
	Gamepad int32,
	LeftMotor float32,
	RightMotor float32,
	Duration float32,
)

//go:wasmimport _raylib _IsMouseButtonPressed
//go:noescape
func isMouseButtonPressed(
	ret cptr,
	Button int32,
)

//go:wasmimport _raylib _IsMouseButtonDown
//go:noescape
func isMouseButtonDown(
	ret cptr,
	Button int32,
)

//go:wasmimport _raylib _IsMouseButtonReleased
//go:noescape
func isMouseButtonReleased(
	ret cptr,
	Button int32,
)

//go:wasmimport _raylib _IsMouseButtonUp
//go:noescape
func isMouseButtonUp(
	ret cptr,
	Button int32,
)

//go:wasmimport _raylib _GetMouseX
//go:noescape
func getMouseX(
	ret int32,
)

//go:wasmimport _raylib _GetMouseY
//go:noescape
func getMouseY(
	ret int32,
)

//go:wasmimport _raylib _GetMousePosition
//go:noescape
func getMousePosition(
	ret cptr,
)

//go:wasmimport _raylib _GetMouseDelta
//go:noescape
func getMouseDelta(
	ret cptr,
)

//go:wasmimport _raylib _SetMousePosition
//go:noescape
func setMousePosition(
	X int32,
	Y int32,
)

//go:wasmimport _raylib _SetMouseOffset
//go:noescape
func setMouseOffset(
	OffsetX int32,
	OffsetY int32,
)

//go:wasmimport _raylib _SetMouseScale
//go:noescape
func setMouseScale(
	ScaleX float32,
	ScaleY float32,
)

//go:wasmimport _raylib _GetMouseWheelMove
//go:noescape
func getMouseWheelMove(
	ret float32,
)

//go:wasmimport _raylib _GetMouseWheelMoveV
//go:noescape
func getMouseWheelMoveV(
	ret cptr,
)

//go:wasmimport _raylib _SetMouseCursor
//go:noescape
func setMouseCursor(
	Cursor int32,
)

//go:wasmimport _raylib _GetTouchX
//go:noescape
func getTouchX(
	ret int32,
)

//go:wasmimport _raylib _GetTouchY
//go:noescape
func getTouchY(
	ret int32,
)

//go:wasmimport _raylib _GetTouchPosition
//go:noescape
func getTouchPosition(
	ret cptr,
	Index int32,
)

//go:wasmimport _raylib _GetTouchPointId
//go:noescape
func getTouchPointId(
	ret int32,
	Index int32,
)

//go:wasmimport _raylib _GetTouchPointCount
//go:noescape
func getTouchPointCount(
	ret int32,
)

//go:wasmimport _raylib _SetGesturesEnabled
//go:noescape
func setGesturesEnabled(
	Flags uint32,
)

//go:wasmimport _raylib _IsGestureDetected
//go:noescape
func isGestureDetected(
	ret cptr,
	Gesture uint32,
)

//go:wasmimport _raylib _GetGestureDetected
//go:noescape
func getGestureDetected(
	ret int32,
)

//go:wasmimport _raylib _GetGestureHoldDuration
//go:noescape
func getGestureHoldDuration(
	ret float32,
)

//go:wasmimport _raylib _GetGestureDragVector
//go:noescape
func getGestureDragVector(
	ret cptr,
)

//go:wasmimport _raylib _GetGestureDragAngle
//go:noescape
func getGestureDragAngle(
	ret float32,
)

//go:wasmimport _raylib _GetGesturePinchVector
//go:noescape
func getGesturePinchVector(
	ret cptr,
)

//go:wasmimport _raylib _GetGesturePinchAngle
//go:noescape
func getGesturePinchAngle(
	ret float32,
)

//go:wasmimport _raylib _UpdateCamera
//go:noescape
func updateCamera(
	Camera cptr,
	Mode int32,
)

//go:wasmimport _raylib _UpdateCameraPro
//go:noescape
func updateCameraPro(
	Camera cptr,
	Movement cptr,
	Rotation cptr,
	Zoom float32,
)

//go:wasmimport _raylib _SetShapesTexture
//go:noescape
func setShapesTexture(
	Texture cptr,
	Source cptr,
)

//go:wasmimport _raylib _GetShapesTexture
//go:noescape
func getShapesTexture(
	ret cptr,
)

//go:wasmimport _raylib _GetShapesTextureRectangle
//go:noescape
func getShapesTextureRectangle(
	ret cptr,
)

//go:wasmimport _raylib _DrawPixel
//go:noescape
func drawPixel(
	PosX int32,
	PosY int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawPixelV
//go:noescape
func drawPixelV(
	Position cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawLine
//go:noescape
func drawLine(
	StartPosX int32,
	StartPosY int32,
	EndPosX int32,
	EndPosY int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawLineV
//go:noescape
func drawLineV(
	StartPos cptr,
	EndPos cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawLineEx
//go:noescape
func drawLineEx(
	StartPos cptr,
	EndPos cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawLineStrip
//go:noescape
func drawLineStrip(
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawLineBezier
//go:noescape
func drawLineBezier(
	StartPos cptr,
	EndPos cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawLineDashed
//go:noescape
func drawLineDashed(
	StartPos cptr,
	EndPos cptr,
	DashSize int32,
	SpaceSize int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircle
//go:noescape
func drawCircle(
	CenterX int32,
	CenterY int32,
	Radius float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircleSector
//go:noescape
func drawCircleSector(
	Center cptr,
	Radius float32,
	StartAngle float32,
	EndAngle float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircleSectorLines
//go:noescape
func drawCircleSectorLines(
	Center cptr,
	Radius float32,
	StartAngle float32,
	EndAngle float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircleGradient
//go:noescape
func drawCircleGradient(
	CenterX int32,
	CenterY int32,
	Radius float32,
	Inner cptr,
	Outer cptr,
)

//go:wasmimport _raylib _DrawCircleV
//go:noescape
func drawCircleV(
	Center cptr,
	Radius float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircleLines
//go:noescape
func drawCircleLines(
	CenterX int32,
	CenterY int32,
	Radius float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircleLinesV
//go:noescape
func drawCircleLinesV(
	Center cptr,
	Radius float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawEllipse
//go:noescape
func drawEllipse(
	CenterX int32,
	CenterY int32,
	RadiusH float32,
	RadiusV float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawEllipseV
//go:noescape
func drawEllipseV(
	Center cptr,
	RadiusH float32,
	RadiusV float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawEllipseLines
//go:noescape
func drawEllipseLines(
	CenterX int32,
	CenterY int32,
	RadiusH float32,
	RadiusV float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawEllipseLinesV
//go:noescape
func drawEllipseLinesV(
	Center cptr,
	RadiusH float32,
	RadiusV float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRing
//go:noescape
func drawRing(
	Center cptr,
	InnerRadius float32,
	OuterRadius float32,
	StartAngle float32,
	EndAngle float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRingLines
//go:noescape
func drawRingLines(
	Center cptr,
	InnerRadius float32,
	OuterRadius float32,
	StartAngle float32,
	EndAngle float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangle
//go:noescape
func drawRectangle(
	PosX int32,
	PosY int32,
	Width int32,
	Height int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleV
//go:noescape
func drawRectangleV(
	Position cptr,
	Size cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleRec
//go:noescape
func drawRectangleRec(
	Rec cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectanglePro
//go:noescape
func drawRectanglePro(
	Rec cptr,
	Origin cptr,
	Rotation float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleGradientV
//go:noescape
func drawRectangleGradientV(
	PosX int32,
	PosY int32,
	Width int32,
	Height int32,
	Top cptr,
	Bottom cptr,
)

//go:wasmimport _raylib _DrawRectangleGradientH
//go:noescape
func drawRectangleGradientH(
	PosX int32,
	PosY int32,
	Width int32,
	Height int32,
	Left cptr,
	Right cptr,
)

//go:wasmimport _raylib _DrawRectangleGradientEx
//go:noescape
func drawRectangleGradientEx(
	Rec cptr,
	TopLeft cptr,
	BottomLeft cptr,
	BottomRight cptr,
	TopRight cptr,
)

//go:wasmimport _raylib _DrawRectangleLines
//go:noescape
func drawRectangleLines(
	PosX int32,
	PosY int32,
	Width int32,
	Height int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleLinesEx
//go:noescape
func drawRectangleLinesEx(
	Rec cptr,
	LineThick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleRounded
//go:noescape
func drawRectangleRounded(
	Rec cptr,
	Roundness float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleRoundedLines
//go:noescape
func drawRectangleRoundedLines(
	Rec cptr,
	Roundness float32,
	Segments int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawRectangleRoundedLinesEx
//go:noescape
func drawRectangleRoundedLinesEx(
	Rec cptr,
	Roundness float32,
	Segments int32,
	LineThick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangle
//go:noescape
func drawTriangle(
	V1 cptr,
	V2 cptr,
	V3 cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangleLines
//go:noescape
func drawTriangleLines(
	V1 cptr,
	V2 cptr,
	V3 cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangleFan
//go:noescape
func drawTriangleFan(
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangleStrip
//go:noescape
func drawTriangleStrip(
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawPoly
//go:noescape
func drawPoly(
	Center cptr,
	Sides int32,
	Radius float32,
	Rotation float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawPolyLines
//go:noescape
func drawPolyLines(
	Center cptr,
	Sides int32,
	Radius float32,
	Rotation float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawPolyLinesEx
//go:noescape
func drawPolyLinesEx(
	Center cptr,
	Sides int32,
	Radius float32,
	Rotation float32,
	LineThick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineLinear
//go:noescape
func drawSplineLinear(
	Points cptr,
	PointCount int32,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineBasis
//go:noescape
func drawSplineBasis(
	Points cptr,
	PointCount int32,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineCatmullRom
//go:noescape
func drawSplineCatmullRom(
	Points cptr,
	PointCount int32,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineBezierQuadratic
//go:noescape
func drawSplineBezierQuadratic(
	Points cptr,
	PointCount int32,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineBezierCubic
//go:noescape
func drawSplineBezierCubic(
	Points cptr,
	PointCount int32,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineSegmentLinear
//go:noescape
func drawSplineSegmentLinear(
	P1 cptr,
	P2 cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineSegmentBasis
//go:noescape
func drawSplineSegmentBasis(
	P1 cptr,
	P2 cptr,
	P3 cptr,
	P4 cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineSegmentCatmullRom
//go:noescape
func drawSplineSegmentCatmullRom(
	P1 cptr,
	P2 cptr,
	P3 cptr,
	P4 cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineSegmentBezierQuadratic
//go:noescape
func drawSplineSegmentBezierQuadratic(
	P1 cptr,
	C2 cptr,
	P3 cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSplineSegmentBezierCubic
//go:noescape
func drawSplineSegmentBezierCubic(
	P1 cptr,
	C2 cptr,
	C3 cptr,
	P4 cptr,
	Thick float32,
	Color cptr,
)

//go:wasmimport _raylib _GetSplinePointLinear
//go:noescape
func getSplinePointLinear(
	ret cptr,
	StartPos cptr,
	EndPos cptr,
	T float32,
)

//go:wasmimport _raylib _GetSplinePointBasis
//go:noescape
func getSplinePointBasis(
	ret cptr,
	P1 cptr,
	P2 cptr,
	P3 cptr,
	P4 cptr,
	T float32,
)

//go:wasmimport _raylib _GetSplinePointCatmullRom
//go:noescape
func getSplinePointCatmullRom(
	ret cptr,
	P1 cptr,
	P2 cptr,
	P3 cptr,
	P4 cptr,
	T float32,
)

//go:wasmimport _raylib _GetSplinePointBezierQuad
//go:noescape
func getSplinePointBezierQuad(
	ret cptr,
	P1 cptr,
	C2 cptr,
	P3 cptr,
	T float32,
)

//go:wasmimport _raylib _GetSplinePointBezierCubic
//go:noescape
func getSplinePointBezierCubic(
	ret cptr,
	P1 cptr,
	C2 cptr,
	C3 cptr,
	P4 cptr,
	T float32,
)

//go:wasmimport _raylib _CheckCollisionRecs
//go:noescape
func checkCollisionRecs(
	ret cptr,
	Rec1 cptr,
	Rec2 cptr,
)

//go:wasmimport _raylib _CheckCollisionCircles
//go:noescape
func checkCollisionCircles(
	ret cptr,
	Center1 cptr,
	Radius1 float32,
	Center2 cptr,
	Radius2 float32,
)

//go:wasmimport _raylib _CheckCollisionCircleRec
//go:noescape
func checkCollisionCircleRec(
	ret cptr,
	Center cptr,
	Radius float32,
	Rec cptr,
)

//go:wasmimport _raylib _CheckCollisionCircleLine
//go:noescape
func checkCollisionCircleLine(
	ret cptr,
	Center cptr,
	Radius float32,
	P1 cptr,
	P2 cptr,
)

//go:wasmimport _raylib _CheckCollisionPointRec
//go:noescape
func checkCollisionPointRec(
	ret cptr,
	Point cptr,
	Rec cptr,
)

//go:wasmimport _raylib _CheckCollisionPointCircle
//go:noescape
func checkCollisionPointCircle(
	ret cptr,
	Point cptr,
	Center cptr,
	Radius float32,
)

//go:wasmimport _raylib _CheckCollisionPointTriangle
//go:noescape
func checkCollisionPointTriangle(
	ret cptr,
	Point cptr,
	P1 cptr,
	P2 cptr,
	P3 cptr,
)

//go:wasmimport _raylib _CheckCollisionPointLine
//go:noescape
func checkCollisionPointLine(
	ret cptr,
	Point cptr,
	P1 cptr,
	P2 cptr,
	Threshold int32,
)

//go:wasmimport _raylib _CheckCollisionPointPoly
//go:noescape
func checkCollisionPointPoly(
	ret cptr,
	Point cptr,
	Points cptr,
	PointCount int32,
)

//go:wasmimport _raylib _CheckCollisionLines
//go:noescape
func checkCollisionLines(
	ret cptr,
	StartPos1 cptr,
	EndPos1 cptr,
	StartPos2 cptr,
	EndPos2 cptr,
	CollisionPoint cptr,
)

//go:wasmimport _raylib _GetCollisionRec
//go:noescape
func getCollisionRec(
	ret cptr,
	Rec1 cptr,
	Rec2 cptr,
)

//go:wasmimport _raylib _LoadImage
//go:noescape
func loadImage(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadImageRaw
//go:noescape
func loadImageRaw(
	ret cptr,
	FileName cptr,
	Width int32,
	Height int32,
	Format int32,
	HeaderSize int32,
)

//go:wasmimport _raylib _LoadImageAnim
//go:noescape
func loadImageAnim(
	ret cptr,
	FileName cptr,
	Frames cptr,
)

//go:wasmimport _raylib _LoadImageAnimFromMemory
//go:noescape
func loadImageAnimFromMemory(
	ret cptr,
	FileType cptr,
	FileData cptr,
	DataSize int32,
	Frames cptr,
)

//go:wasmimport _raylib _LoadImageFromMemory
//go:noescape
func loadImageFromMemory(
	ret cptr,
	FileType cptr,
	FileData cptr,
	DataSize int32,
)

//go:wasmimport _raylib _LoadImageFromTexture
//go:noescape
func loadImageFromTexture(
	ret cptr,
	Texture cptr,
)

//go:wasmimport _raylib _LoadImageFromScreen
//go:noescape
func loadImageFromScreen(
	ret cptr,
)

//go:wasmimport _raylib _IsImageValid
//go:noescape
func isImageValid(
	ret cptr,
	Image cptr,
)

//go:wasmimport _raylib _UnloadImage
//go:noescape
func unloadImage(
	Image cptr,
)

//go:wasmimport _raylib _ExportImage
//go:noescape
func exportImage(
	ret cptr,
	Image cptr,
	FileName cptr,
)

//go:wasmimport _raylib _ExportImageToMemory
//go:noescape
func exportImageToMemory(
	ret cptr,
	Image cptr,
	FileType cptr,
	FileSize cptr,
)

//go:wasmimport _raylib _ExportImageAsCode
//go:noescape
func exportImageAsCode(
	ret cptr,
	Image cptr,
	FileName cptr,
)

//go:wasmimport _raylib _GenImageColor
//go:noescape
func genImageColor(
	ret cptr,
	Width int32,
	Height int32,
	Color cptr,
)

//go:wasmimport _raylib _GenImageGradientLinear
//go:noescape
func genImageGradientLinear(
	ret cptr,
	Width int32,
	Height int32,
	Direction int32,
	Start cptr,
	End cptr,
)

//go:wasmimport _raylib _GenImageGradientRadial
//go:noescape
func genImageGradientRadial(
	ret cptr,
	Width int32,
	Height int32,
	Density float32,
	Inner cptr,
	Outer cptr,
)

//go:wasmimport _raylib _GenImageGradientSquare
//go:noescape
func genImageGradientSquare(
	ret cptr,
	Width int32,
	Height int32,
	Density float32,
	Inner cptr,
	Outer cptr,
)

//go:wasmimport _raylib _GenImageChecked
//go:noescape
func genImageChecked(
	ret cptr,
	Width int32,
	Height int32,
	ChecksX int32,
	ChecksY int32,
	Col1 cptr,
	Col2 cptr,
)

//go:wasmimport _raylib _GenImageWhiteNoise
//go:noescape
func genImageWhiteNoise(
	ret cptr,
	Width int32,
	Height int32,
	Factor float32,
)

//go:wasmimport _raylib _GenImagePerlinNoise
//go:noescape
func genImagePerlinNoise(
	ret cptr,
	Width int32,
	Height int32,
	OffsetX int32,
	OffsetY int32,
	Scale float32,
)

//go:wasmimport _raylib _GenImageCellular
//go:noescape
func genImageCellular(
	ret cptr,
	Width int32,
	Height int32,
	TileSize int32,
)

//go:wasmimport _raylib _GenImageText
//go:noescape
func genImageText(
	ret cptr,
	Width int32,
	Height int32,
	Text cptr,
)

//go:wasmimport _raylib _ImageCopy
//go:noescape
func imageCopy(
	ret cptr,
	Image cptr,
)

//go:wasmimport _raylib _ImageFromImage
//go:noescape
func imageFromImage(
	ret cptr,
	Image cptr,
	Rec cptr,
)

//go:wasmimport _raylib _ImageFromChannel
//go:noescape
func imageFromChannel(
	ret cptr,
	Image cptr,
	SelectedChannel int32,
)

//go:wasmimport _raylib _ImageText
//go:noescape
func imageText(
	ret cptr,
	Text cptr,
	FontSize int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageTextEx
//go:noescape
func imageTextEx(
	ret cptr,
	Font cptr,
	Text cptr,
	FontSize float32,
	Spacing float32,
	Tint cptr,
)

//go:wasmimport _raylib _ImageFormat
//go:noescape
func imageFormat(
	Image cptr,
	NewFormat int32,
)

//go:wasmimport _raylib _ImageToPOT
//go:noescape
func imageToPOT(
	Image cptr,
	Fill cptr,
)

//go:wasmimport _raylib _ImageCrop
//go:noescape
func imageCrop(
	Image cptr,
	Crop cptr,
)

//go:wasmimport _raylib _ImageAlphaCrop
//go:noescape
func imageAlphaCrop(
	Image cptr,
	Threshold float32,
)

//go:wasmimport _raylib _ImageAlphaClear
//go:noescape
func imageAlphaClear(
	Image cptr,
	Color cptr,
	Threshold float32,
)

//go:wasmimport _raylib _ImageAlphaMask
//go:noescape
func imageAlphaMask(
	Image cptr,
	AlphaMask cptr,
)

//go:wasmimport _raylib _ImageAlphaPremultiply
//go:noescape
func imageAlphaPremultiply(
	Image cptr,
)

//go:wasmimport _raylib _ImageBlurGaussian
//go:noescape
func imageBlurGaussian(
	Image cptr,
	BlurSize int32,
)

//go:wasmimport _raylib _ImageKernelConvolution
//go:noescape
func imageKernelConvolution(
	Image cptr,
	Kernel cptr,
	KernelSize int32,
)

//go:wasmimport _raylib _ImageResize
//go:noescape
func imageResize(
	Image cptr,
	NewWidth int32,
	NewHeight int32,
)

//go:wasmimport _raylib _ImageResizeNN
//go:noescape
func imageResizeNN(
	Image cptr,
	NewWidth int32,
	NewHeight int32,
)

//go:wasmimport _raylib _ImageResizeCanvas
//go:noescape
func imageResizeCanvas(
	Image cptr,
	NewWidth int32,
	NewHeight int32,
	OffsetX int32,
	OffsetY int32,
	Fill cptr,
)

//go:wasmimport _raylib _ImageMipmaps
//go:noescape
func imageMipmaps(
	Image cptr,
)

//go:wasmimport _raylib _ImageDither
//go:noescape
func imageDither(
	Image cptr,
	RBpp int32,
	GBpp int32,
	BBpp int32,
	ABpp int32,
)

//go:wasmimport _raylib _ImageFlipVertical
//go:noescape
func imageFlipVertical(
	Image cptr,
)

//go:wasmimport _raylib _ImageFlipHorizontal
//go:noescape
func imageFlipHorizontal(
	Image cptr,
)

//go:wasmimport _raylib _ImageRotate
//go:noescape
func imageRotate(
	Image cptr,
	Degrees int32,
)

//go:wasmimport _raylib _ImageRotateCW
//go:noescape
func imageRotateCW(
	Image cptr,
)

//go:wasmimport _raylib _ImageRotateCCW
//go:noescape
func imageRotateCCW(
	Image cptr,
)

//go:wasmimport _raylib _ImageColorTint
//go:noescape
func imageColorTint(
	Image cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageColorInvert
//go:noescape
func imageColorInvert(
	Image cptr,
)

//go:wasmimport _raylib _ImageColorGrayscale
//go:noescape
func imageColorGrayscale(
	Image cptr,
)

//go:wasmimport _raylib _ImageColorContrast
//go:noescape
func imageColorContrast(
	Image cptr,
	Contrast float32,
)

//go:wasmimport _raylib _ImageColorBrightness
//go:noescape
func imageColorBrightness(
	Image cptr,
	Brightness int32,
)

//go:wasmimport _raylib _ImageColorReplace
//go:noescape
func imageColorReplace(
	Image cptr,
	Color cptr,
	Replace cptr,
)

//go:wasmimport _raylib _LoadImageColors
//go:noescape
func loadImageColors(
	ret cptr,
	Image cptr,
)

//go:wasmimport _raylib _LoadImagePalette
//go:noescape
func loadImagePalette(
	ret cptr,
	Image cptr,
	MaxPaletteSize int32,
	ColorCount cptr,
)

//go:wasmimport _raylib _UnloadImageColors
//go:noescape
func unloadImageColors(
	Colors cptr,
)

//go:wasmimport _raylib _UnloadImagePalette
//go:noescape
func unloadImagePalette(
	Colors cptr,
)

//go:wasmimport _raylib _GetImageAlphaBorder
//go:noescape
func getImageAlphaBorder(
	ret cptr,
	Image cptr,
	Threshold float32,
)

//go:wasmimport _raylib _GetImageColor
//go:noescape
func getImageColor(
	ret cptr,
	Image cptr,
	X int32,
	Y int32,
)

//go:wasmimport _raylib _ImageClearBackground
//go:noescape
func imageClearBackground(
	Dst cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawPixel
//go:noescape
func imageDrawPixel(
	Dst cptr,
	PosX int32,
	PosY int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawPixelV
//go:noescape
func imageDrawPixelV(
	Dst cptr,
	Position cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawLine
//go:noescape
func imageDrawLine(
	Dst cptr,
	StartPosX int32,
	StartPosY int32,
	EndPosX int32,
	EndPosY int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawLineV
//go:noescape
func imageDrawLineV(
	Dst cptr,
	Start cptr,
	End cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawLineEx
//go:noescape
func imageDrawLineEx(
	Dst cptr,
	Start cptr,
	End cptr,
	Thick int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawCircle
//go:noescape
func imageDrawCircle(
	Dst cptr,
	CenterX int32,
	CenterY int32,
	Radius int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawCircleV
//go:noescape
func imageDrawCircleV(
	Dst cptr,
	Center cptr,
	Radius int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawCircleLines
//go:noescape
func imageDrawCircleLines(
	Dst cptr,
	CenterX int32,
	CenterY int32,
	Radius int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawCircleLinesV
//go:noescape
func imageDrawCircleLinesV(
	Dst cptr,
	Center cptr,
	Radius int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawRectangle
//go:noescape
func imageDrawRectangle(
	Dst cptr,
	PosX int32,
	PosY int32,
	Width int32,
	Height int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawRectangleV
//go:noescape
func imageDrawRectangleV(
	Dst cptr,
	Position cptr,
	Size cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawRectangleRec
//go:noescape
func imageDrawRectangleRec(
	Dst cptr,
	Rec cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawRectangleLines
//go:noescape
func imageDrawRectangleLines(
	Dst cptr,
	Rec cptr,
	Thick int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawTriangle
//go:noescape
func imageDrawTriangle(
	Dst cptr,
	V1 cptr,
	V2 cptr,
	V3 cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawTriangleEx
//go:noescape
func imageDrawTriangleEx(
	Dst cptr,
	V1 cptr,
	V2 cptr,
	V3 cptr,
	C1 cptr,
	C2 cptr,
	C3 cptr,
)

//go:wasmimport _raylib _ImageDrawTriangleLines
//go:noescape
func imageDrawTriangleLines(
	Dst cptr,
	V1 cptr,
	V2 cptr,
	V3 cptr,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawTriangleFan
//go:noescape
func imageDrawTriangleFan(
	Dst cptr,
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawTriangleStrip
//go:noescape
func imageDrawTriangleStrip(
	Dst cptr,
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDraw
//go:noescape
func imageDraw(
	Dst cptr,
	Src cptr,
	SrcRec cptr,
	DstRec cptr,
	Tint cptr,
)

//go:wasmimport _raylib _ImageDrawText
//go:noescape
func imageDrawText(
	Dst cptr,
	Text cptr,
	PosX int32,
	PosY int32,
	FontSize int32,
	Color cptr,
)

//go:wasmimport _raylib _ImageDrawTextEx
//go:noescape
func imageDrawTextEx(
	Dst cptr,
	Font cptr,
	Text cptr,
	Position cptr,
	FontSize float32,
	Spacing float32,
	Tint cptr,
)

//go:wasmimport _raylib _LoadTexture
//go:noescape
func loadTexture(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadTextureFromImage
//go:noescape
func loadTextureFromImage(
	ret cptr,
	Image cptr,
)

//go:wasmimport _raylib _LoadTextureCubemap
//go:noescape
func loadTextureCubemap(
	ret cptr,
	Image cptr,
	Layout int32,
)

//go:wasmimport _raylib _LoadRenderTexture
//go:noescape
func loadRenderTexture(
	ret cptr,
	Width int32,
	Height int32,
)

//go:wasmimport _raylib _IsTextureValid
//go:noescape
func isTextureValid(
	ret cptr,
	Texture cptr,
)

//go:wasmimport _raylib _UnloadTexture
//go:noescape
func unloadTexture(
	Texture cptr,
)

//go:wasmimport _raylib _IsRenderTextureValid
//go:noescape
func isRenderTextureValid(
	ret cptr,
	Target cptr,
)

//go:wasmimport _raylib _UnloadRenderTexture
//go:noescape
func unloadRenderTexture(
	Target cptr,
)

//go:wasmimport _raylib _UpdateTexture
//go:noescape
func updateTexture(
	Texture cptr,
	Pixels cptr,
)

//go:wasmimport _raylib _UpdateTextureRec
//go:noescape
func updateTextureRec(
	Texture cptr,
	Rec cptr,
	Pixels cptr,
)

//go:wasmimport _raylib _GenTextureMipmaps
//go:noescape
func genTextureMipmaps(
	Texture cptr,
)

//go:wasmimport _raylib _SetTextureFilter
//go:noescape
func setTextureFilter(
	Texture cptr,
	Filter int32,
)

//go:wasmimport _raylib _SetTextureWrap
//go:noescape
func setTextureWrap(
	Texture cptr,
	Wrap int32,
)

//go:wasmimport _raylib _DrawTexture
//go:noescape
func drawTexture(
	Texture cptr,
	PosX int32,
	PosY int32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextureV
//go:noescape
func drawTextureV(
	Texture cptr,
	Position cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextureEx
//go:noescape
func drawTextureEx(
	Texture cptr,
	Position cptr,
	Rotation float32,
	Scale float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextureRec
//go:noescape
func drawTextureRec(
	Texture cptr,
	Source cptr,
	Position cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTexturePro
//go:noescape
func drawTexturePro(
	Texture cptr,
	Source cptr,
	Dest cptr,
	Origin cptr,
	Rotation float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextureNPatch
//go:noescape
func drawTextureNPatch(
	Texture cptr,
	NPatchInfo cptr,
	Dest cptr,
	Origin cptr,
	Rotation float32,
	Tint cptr,
)

//go:wasmimport _raylib _ColorIsEqual
//go:noescape
func colorIsEqual(
	ret cptr,
	Col1 cptr,
	Col2 cptr,
)

//go:wasmimport _raylib _Fade
//go:noescape
func fade(
	ret cptr,
	Color cptr,
	Alpha float32,
)

//go:wasmimport _raylib _ColorToInt
//go:noescape
func colorToInt(
	ret int32,
	Color cptr,
)

//go:wasmimport _raylib _ColorNormalize
//go:noescape
func colorNormalize(
	ret cptr,
	Color cptr,
)

//go:wasmimport _raylib _ColorFromNormalized
//go:noescape
func colorFromNormalized(
	ret cptr,
	Normalized cptr,
)

//go:wasmimport _raylib _ColorToHSV
//go:noescape
func colorToHSV(
	ret cptr,
	Color cptr,
)

//go:wasmimport _raylib _ColorFromHSV
//go:noescape
func colorFromHSV(
	ret cptr,
	Hue float32,
	Saturation float32,
	Value float32,
)

//go:wasmimport _raylib _ColorTint
//go:noescape
func colorTint(
	ret cptr,
	Color cptr,
	Tint cptr,
)

//go:wasmimport _raylib _ColorBrightness
//go:noescape
func colorBrightness(
	ret cptr,
	Color cptr,
	Factor float32,
)

//go:wasmimport _raylib _ColorContrast
//go:noescape
func colorContrast(
	ret cptr,
	Color cptr,
	Contrast float32,
)

//go:wasmimport _raylib _ColorAlpha
//go:noescape
func colorAlpha(
	ret cptr,
	Color cptr,
	Alpha float32,
)

//go:wasmimport _raylib _ColorAlphaBlend
//go:noescape
func colorAlphaBlend(
	ret cptr,
	Dst cptr,
	Src cptr,
	Tint cptr,
)

//go:wasmimport _raylib _ColorLerp
//go:noescape
func colorLerp(
	ret cptr,
	Color1 cptr,
	Color2 cptr,
	Factor float32,
)

//go:wasmimport _raylib _GetColor
//go:noescape
func getColor(
	ret cptr,
	HexValue uint32,
)

//go:wasmimport _raylib _GetPixelColor
//go:noescape
func getPixelColor(
	ret cptr,
	SrcPtr cptr,
	Format int32,
)

//go:wasmimport _raylib _SetPixelColor
//go:noescape
func setPixelColor(
	DstPtr cptr,
	Color cptr,
	Format int32,
)

//go:wasmimport _raylib _GetPixelDataSize
//go:noescape
func getPixelDataSize(
	ret int32,
	Width int32,
	Height int32,
	Format int32,
)

//go:wasmimport _raylib _GetFontDefault
//go:noescape
func getFontDefault(
	ret cptr,
)

//go:wasmimport _raylib _LoadFont
//go:noescape
func loadFont(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadFontEx
//go:noescape
func loadFontEx(
	ret cptr,
	FileName cptr,
	FontSize int32,
	Codepoints cptr,
	CodepointCount int32,
)

//go:wasmimport _raylib _LoadFontFromImage
//go:noescape
func loadFontFromImage(
	ret cptr,
	Image cptr,
	Key cptr,
	FirstChar int32,
)

//go:wasmimport _raylib _LoadFontFromMemory
//go:noescape
func loadFontFromMemory(
	ret cptr,
	FileType cptr,
	FileData cptr,
	DataSize int32,
	FontSize int32,
	Codepoints cptr,
	CodepointCount int32,
)

//go:wasmimport _raylib _IsFontValid
//go:noescape
func isFontValid(
	ret cptr,
	Font cptr,
)

//go:wasmimport _raylib _LoadFontData
//go:noescape
func loadFontData(
	ret cptr,
	FileData cptr,
	DataSize int32,
	FontSize int32,
	Codepoints cptr,
	CodepointCount int32,
	Type int32,
	GlyphCount cptr,
)

//go:wasmimport _raylib _GenImageFontAtlas
//go:noescape
func genImageFontAtlas(
	ret cptr,
	Glyphs cptr,
	GlyphRecs cptr,
	GlyphCount int32,
	FontSize int32,
	Padding int32,
	PackMethod int32,
)

//go:wasmimport _raylib _UnloadFontData
//go:noescape
func unloadFontData(
	Glyphs cptr,
	GlyphCount int32,
)

//go:wasmimport _raylib _UnloadFont
//go:noescape
func unloadFont(
	Font cptr,
)

//go:wasmimport _raylib _ExportFontAsCode
//go:noescape
func exportFontAsCode(
	ret cptr,
	Font cptr,
	FileName cptr,
)

//go:wasmimport _raylib _DrawFPS
//go:noescape
func drawFPS(
	PosX int32,
	PosY int32,
)

//go:wasmimport _raylib _DrawText
//go:noescape
func drawText(
	Text cptr,
	PosX int32,
	PosY int32,
	FontSize int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawTextEx
//go:noescape
func drawTextEx(
	Font cptr,
	Text cptr,
	Position cptr,
	FontSize float32,
	Spacing float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextPro
//go:noescape
func drawTextPro(
	Font cptr,
	Text cptr,
	Position cptr,
	Origin cptr,
	Rotation float32,
	FontSize float32,
	Spacing float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextCodepoint
//go:noescape
func drawTextCodepoint(
	Font cptr,
	Codepoint int32,
	Position cptr,
	FontSize float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawTextCodepoints
//go:noescape
func drawTextCodepoints(
	Font cptr,
	Codepoints cptr,
	CodepointCount int32,
	Position cptr,
	FontSize float32,
	Spacing float32,
	Tint cptr,
)

//go:wasmimport _raylib _SetTextLineSpacing
//go:noescape
func setTextLineSpacing(
	Spacing int32,
)

//go:wasmimport _raylib _MeasureText
//go:noescape
func measureText(
	ret int32,
	Text cptr,
	FontSize int32,
)

//go:wasmimport _raylib _MeasureTextEx
//go:noescape
func measureTextEx(
	ret cptr,
	Font cptr,
	Text cptr,
	FontSize float32,
	Spacing float32,
)

//go:wasmimport _raylib _GetGlyphIndex
//go:noescape
func getGlyphIndex(
	ret int32,
	Font cptr,
	Codepoint int32,
)

//go:wasmimport _raylib _GetGlyphInfo
//go:noescape
func getGlyphInfo(
	ret cptr,
	Font cptr,
	Codepoint int32,
)

//go:wasmimport _raylib _GetGlyphAtlasRec
//go:noescape
func getGlyphAtlasRec(
	ret cptr,
	Font cptr,
	Codepoint int32,
)

//go:wasmimport _raylib _LoadUTF8
//go:noescape
func loadUTF8(
	ret cptr,
	Codepoints cptr,
	Length int32,
)

//go:wasmimport _raylib _UnloadUTF8
//go:noescape
func unloadUTF8(
	Text cptr,
)

//go:wasmimport _raylib _LoadCodepoints
//go:noescape
func loadCodepoints(
	ret cptr,
	Text cptr,
	Count cptr,
)

//go:wasmimport _raylib _UnloadCodepoints
//go:noescape
func unloadCodepoints(
	Codepoints cptr,
)

//go:wasmimport _raylib _GetCodepointCount
//go:noescape
func getCodepointCount(
	ret int32,
	Text cptr,
)

//go:wasmimport _raylib _GetCodepoint
//go:noescape
func getCodepoint(
	ret int32,
	Text cptr,
	CodepointSize cptr,
)

//go:wasmimport _raylib _GetCodepointNext
//go:noescape
func getCodepointNext(
	ret int32,
	Text cptr,
	CodepointSize cptr,
)

//go:wasmimport _raylib _GetCodepointPrevious
//go:noescape
func getCodepointPrevious(
	ret int32,
	Text cptr,
	CodepointSize cptr,
)

//go:wasmimport _raylib _CodepointToUTF8
//go:noescape
func codepointToUTF8(
	ret cptr,
	Codepoint int32,
	Utf8Size cptr,
)

//go:wasmimport _raylib _LoadTextLines
//go:noescape
func loadTextLines(
	ret cptr,
	Text cptr,
	Count cptr,
)

//go:wasmimport _raylib _UnloadTextLines
//go:noescape
func unloadTextLines(
	Text cptr,
	LineCount int32,
)

//go:wasmimport _raylib _TextCopy
//go:noescape
func textCopy(
	ret int32,
	Dst cptr,
	Src cptr,
)

//go:wasmimport _raylib _TextIsEqual
//go:noescape
func textIsEqual(
	ret cptr,
	Text1 cptr,
	Text2 cptr,
)

//go:wasmimport _raylib _TextLength
//go:noescape
func textLength(
	ret uint32,
	Text cptr,
)

//go:wasmimport _raylib _TextFormat
//go:noescape
func textFormat(
	ret cptr,
	Text cptr,
	Args cptr,
)

//go:wasmimport _raylib _TextSubtext
//go:noescape
func textSubtext(
	ret cptr,
	Text cptr,
	Position int32,
	Length int32,
)

//go:wasmimport _raylib _TextRemoveSpaces
//go:noescape
func textRemoveSpaces(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _GetTextBetween
//go:noescape
func getTextBetween(
	ret cptr,
	Text cptr,
	Begin cptr,
	End cptr,
)

//go:wasmimport _raylib _TextReplace
//go:noescape
func textReplace(
	ret cptr,
	Text cptr,
	Search cptr,
	Replacement cptr,
)

//go:wasmimport _raylib _TextReplaceBetween
//go:noescape
func textReplaceBetween(
	ret cptr,
	Text cptr,
	Begin cptr,
	End cptr,
	Replacement cptr,
)

//go:wasmimport _raylib _TextInsert
//go:noescape
func textInsert(
	ret cptr,
	Text cptr,
	Insert cptr,
	Position int32,
)

//go:wasmimport _raylib _TextJoin
//go:noescape
func textJoin(
	ret cptr,
	TextList cptr,
	Count int32,
	Delimiter cptr,
)

//go:wasmimport _raylib _TextSplit
//go:noescape
func textSplit(
	ret cptr,
	Text cptr,
	Delimiter byte,
	Count cptr,
)

//go:wasmimport _raylib _TextAppend
//go:noescape
func textAppend(
	Text cptr,
	Append cptr,
	Position cptr,
)

//go:wasmimport _raylib _TextFindIndex
//go:noescape
func textFindIndex(
	ret int32,
	Text cptr,
	Search cptr,
)

//go:wasmimport _raylib _TextToUpper
//go:noescape
func textToUpper(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _TextToLower
//go:noescape
func textToLower(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _TextToPascal
//go:noescape
func textToPascal(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _TextToSnake
//go:noescape
func textToSnake(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _TextToCamel
//go:noescape
func textToCamel(
	ret cptr,
	Text cptr,
)

//go:wasmimport _raylib _TextToInteger
//go:noescape
func textToInteger(
	ret int32,
	Text cptr,
)

//go:wasmimport _raylib _TextToFloat
//go:noescape
func textToFloat(
	ret float32,
	Text cptr,
)

//go:wasmimport _raylib _DrawLine3D
//go:noescape
func drawLine3D(
	StartPos cptr,
	EndPos cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawPoint3D
//go:noescape
func drawPoint3D(
	Position cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawCircle3D
//go:noescape
func drawCircle3D(
	Center cptr,
	Radius float32,
	RotationAxis cptr,
	RotationAngle float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangle3D
//go:noescape
func drawTriangle3D(
	V1 cptr,
	V2 cptr,
	V3 cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawTriangleStrip3D
//go:noescape
func drawTriangleStrip3D(
	Points cptr,
	PointCount int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCube
//go:noescape
func drawCube(
	Position cptr,
	Width float32,
	Height float32,
	Length float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCubeV
//go:noescape
func drawCubeV(
	Position cptr,
	Size cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawCubeWires
//go:noescape
func drawCubeWires(
	Position cptr,
	Width float32,
	Height float32,
	Length float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCubeWiresV
//go:noescape
func drawCubeWiresV(
	Position cptr,
	Size cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawSphere
//go:noescape
func drawSphere(
	CenterPos cptr,
	Radius float32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSphereEx
//go:noescape
func drawSphereEx(
	CenterPos cptr,
	Radius float32,
	Rings int32,
	Slices int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawSphereWires
//go:noescape
func drawSphereWires(
	CenterPos cptr,
	Radius float32,
	Rings int32,
	Slices int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCylinder
//go:noescape
func drawCylinder(
	Position cptr,
	RadiusTop float32,
	RadiusBottom float32,
	Height float32,
	Slices int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCylinderEx
//go:noescape
func drawCylinderEx(
	StartPos cptr,
	EndPos cptr,
	StartRadius float32,
	EndRadius float32,
	Sides int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCylinderWires
//go:noescape
func drawCylinderWires(
	Position cptr,
	RadiusTop float32,
	RadiusBottom float32,
	Height float32,
	Slices int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCylinderWiresEx
//go:noescape
func drawCylinderWiresEx(
	StartPos cptr,
	EndPos cptr,
	StartRadius float32,
	EndRadius float32,
	Sides int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCapsule
//go:noescape
func drawCapsule(
	StartPos cptr,
	EndPos cptr,
	Radius float32,
	Slices int32,
	Rings int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawCapsuleWires
//go:noescape
func drawCapsuleWires(
	StartPos cptr,
	EndPos cptr,
	Radius float32,
	Slices int32,
	Rings int32,
	Color cptr,
)

//go:wasmimport _raylib _DrawPlane
//go:noescape
func drawPlane(
	CenterPos cptr,
	Size cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawRay
//go:noescape
func drawRay(
	Ray cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawGrid
//go:noescape
func drawGrid(
	Slices int32,
	Spacing float32,
)

//go:wasmimport _raylib _LoadModel
//go:noescape
func loadModel(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadModelFromMesh
//go:noescape
func loadModelFromMesh(
	ret cptr,
	Mesh cptr,
)

//go:wasmimport _raylib _IsModelValid
//go:noescape
func isModelValid(
	ret cptr,
	Model cptr,
)

//go:wasmimport _raylib _UnloadModel
//go:noescape
func unloadModel(
	Model cptr,
)

//go:wasmimport _raylib _GetModelBoundingBox
//go:noescape
func getModelBoundingBox(
	ret cptr,
	Model cptr,
)

//go:wasmimport _raylib _DrawModel
//go:noescape
func drawModel(
	Model cptr,
	Position cptr,
	Scale float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawModelEx
//go:noescape
func drawModelEx(
	Model cptr,
	Position cptr,
	RotationAxis cptr,
	RotationAngle float32,
	Scale cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawModelWires
//go:noescape
func drawModelWires(
	Model cptr,
	Position cptr,
	Scale float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawModelWiresEx
//go:noescape
func drawModelWiresEx(
	Model cptr,
	Position cptr,
	RotationAxis cptr,
	RotationAngle float32,
	Scale cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawModelPoints
//go:noescape
func drawModelPoints(
	Model cptr,
	Position cptr,
	Scale float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawModelPointsEx
//go:noescape
func drawModelPointsEx(
	Model cptr,
	Position cptr,
	RotationAxis cptr,
	RotationAngle float32,
	Scale cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawBoundingBox
//go:noescape
func drawBoundingBox(
	Box cptr,
	Color cptr,
)

//go:wasmimport _raylib _DrawBillboard
//go:noescape
func drawBillboard(
	Camera cptr,
	Texture cptr,
	Position cptr,
	Scale float32,
	Tint cptr,
)

//go:wasmimport _raylib _DrawBillboardRec
//go:noescape
func drawBillboardRec(
	Camera cptr,
	Texture cptr,
	Source cptr,
	Position cptr,
	Size cptr,
	Tint cptr,
)

//go:wasmimport _raylib _DrawBillboardPro
//go:noescape
func drawBillboardPro(
	Camera cptr,
	Texture cptr,
	Source cptr,
	Position cptr,
	Up cptr,
	Size cptr,
	Origin cptr,
	Rotation float32,
	Tint cptr,
)

//go:wasmimport _raylib _UploadMesh
//go:noescape
func uploadMesh(
	Mesh cptr,
	Dynamic cptr,
)

//go:wasmimport _raylib _UpdateMeshBuffer
//go:noescape
func updateMeshBuffer(
	Mesh cptr,
	Index int32,
	Data cptr,
	DataSize int32,
	Offset int32,
)

//go:wasmimport _raylib _UnloadMesh
//go:noescape
func unloadMesh(
	Mesh cptr,
)

//go:wasmimport _raylib _DrawMesh
//go:noescape
func drawMesh(
	Mesh cptr,
	Material cptr,
	Transform cptr,
)

//go:wasmimport _raylib _DrawMeshInstanced
//go:noescape
func drawMeshInstanced(
	Mesh cptr,
	Material cptr,
	Transforms cptr,
	Instances int32,
)

//go:wasmimport _raylib _GetMeshBoundingBox
//go:noescape
func getMeshBoundingBox(
	ret cptr,
	Mesh cptr,
)

//go:wasmimport _raylib _GenMeshTangents
//go:noescape
func genMeshTangents(
	Mesh cptr,
)

//go:wasmimport _raylib _ExportMesh
//go:noescape
func exportMesh(
	ret cptr,
	Mesh cptr,
	FileName cptr,
)

//go:wasmimport _raylib _ExportMeshAsCode
//go:noescape
func exportMeshAsCode(
	ret cptr,
	Mesh cptr,
	FileName cptr,
)

//go:wasmimport _raylib _GenMeshPoly
//go:noescape
func genMeshPoly(
	ret cptr,
	Sides int32,
	Radius float32,
)

//go:wasmimport _raylib _GenMeshPlane
//go:noescape
func genMeshPlane(
	ret cptr,
	Width float32,
	Length float32,
	ResX int32,
	ResZ int32,
)

//go:wasmimport _raylib _GenMeshCube
//go:noescape
func genMeshCube(
	ret cptr,
	Width float32,
	Height float32,
	Length float32,
)

//go:wasmimport _raylib _GenMeshSphere
//go:noescape
func genMeshSphere(
	ret cptr,
	Radius float32,
	Rings int32,
	Slices int32,
)

//go:wasmimport _raylib _GenMeshHemiSphere
//go:noescape
func genMeshHemiSphere(
	ret cptr,
	Radius float32,
	Rings int32,
	Slices int32,
)

//go:wasmimport _raylib _GenMeshCylinder
//go:noescape
func genMeshCylinder(
	ret cptr,
	Radius float32,
	Height float32,
	Slices int32,
)

//go:wasmimport _raylib _GenMeshCone
//go:noescape
func genMeshCone(
	ret cptr,
	Radius float32,
	Height float32,
	Slices int32,
)

//go:wasmimport _raylib _GenMeshTorus
//go:noescape
func genMeshTorus(
	ret cptr,
	Radius float32,
	Size float32,
	RadSeg int32,
	Sides int32,
)

//go:wasmimport _raylib _GenMeshKnot
//go:noescape
func genMeshKnot(
	ret cptr,
	Radius float32,
	Size float32,
	RadSeg int32,
	Sides int32,
)

//go:wasmimport _raylib _GenMeshHeightmap
//go:noescape
func genMeshHeightmap(
	ret cptr,
	Heightmap cptr,
	Size cptr,
)

//go:wasmimport _raylib _GenMeshCubicmap
//go:noescape
func genMeshCubicmap(
	ret cptr,
	Cubicmap cptr,
	CubeSize cptr,
)

//go:wasmimport _raylib _LoadMaterials
//go:noescape
func loadMaterials(
	ret cptr,
	FileName cptr,
	MaterialCount cptr,
)

//go:wasmimport _raylib _LoadMaterialDefault
//go:noescape
func loadMaterialDefault(
	ret cptr,
)

//go:wasmimport _raylib _IsMaterialValid
//go:noescape
func isMaterialValid(
	ret cptr,
	Material cptr,
)

//go:wasmimport _raylib _UnloadMaterial
//go:noescape
func unloadMaterial(
	Material cptr,
)

//go:wasmimport _raylib _SetMaterialTexture
//go:noescape
func setMaterialTexture(
	Material cptr,
	MapType int32,
	Texture cptr,
)

//go:wasmimport _raylib _SetModelMeshMaterial
//go:noescape
func setModelMeshMaterial(
	Model cptr,
	MeshId int32,
	MaterialId int32,
)

//go:wasmimport _raylib _LoadModelAnimations
//go:noescape
func loadModelAnimations(
	ret cptr,
	FileName cptr,
	AnimCount cptr,
)

//go:wasmimport _raylib _UpdateModelAnimation
//go:noescape
func updateModelAnimation(
	Model cptr,
	Anim cptr,
	Frame int32,
)

//go:wasmimport _raylib _UpdateModelAnimationBones
//go:noescape
func updateModelAnimationBones(
	Model cptr,
	Anim cptr,
	Frame int32,
)

//go:wasmimport _raylib _UnloadModelAnimation
//go:noescape
func unloadModelAnimation(
	Anim cptr,
)

//go:wasmimport _raylib _UnloadModelAnimations
//go:noescape
func unloadModelAnimations(
	Animations cptr,
	AnimCount int32,
)

//go:wasmimport _raylib _IsModelAnimationValid
//go:noescape
func isModelAnimationValid(
	ret cptr,
	Model cptr,
	Anim cptr,
)

//go:wasmimport _raylib _CheckCollisionSpheres
//go:noescape
func checkCollisionSpheres(
	ret cptr,
	Center1 cptr,
	Radius1 float32,
	Center2 cptr,
	Radius2 float32,
)

//go:wasmimport _raylib _CheckCollisionBoxes
//go:noescape
func checkCollisionBoxes(
	ret cptr,
	Box1 cptr,
	Box2 cptr,
)

//go:wasmimport _raylib _CheckCollisionBoxSphere
//go:noescape
func checkCollisionBoxSphere(
	ret cptr,
	Box cptr,
	Center cptr,
	Radius float32,
)

//go:wasmimport _raylib _GetRayCollisionSphere
//go:noescape
func getRayCollisionSphere(
	ret cptr,
	Ray cptr,
	Center cptr,
	Radius float32,
)

//go:wasmimport _raylib _GetRayCollisionBox
//go:noescape
func getRayCollisionBox(
	ret cptr,
	Ray cptr,
	Box cptr,
)

//go:wasmimport _raylib _GetRayCollisionMesh
//go:noescape
func getRayCollisionMesh(
	ret cptr,
	Ray cptr,
	Mesh cptr,
	Transform cptr,
)

//go:wasmimport _raylib _GetRayCollisionTriangle
//go:noescape
func getRayCollisionTriangle(
	ret cptr,
	Ray cptr,
	P1 cptr,
	P2 cptr,
	P3 cptr,
)

//go:wasmimport _raylib _GetRayCollisionQuad
//go:noescape
func getRayCollisionQuad(
	ret cptr,
	Ray cptr,
	P1 cptr,
	P2 cptr,
	P3 cptr,
	P4 cptr,
)

//go:wasmimport _raylib _InitAudioDevice
//go:noescape
func initAudioDevice()

//go:wasmimport _raylib _CloseAudioDevice
//go:noescape
func closeAudioDevice()

//go:wasmimport _raylib _IsAudioDeviceReady
//go:noescape
func isAudioDeviceReady(
	ret cptr,
)

//go:wasmimport _raylib _SetMasterVolume
//go:noescape
func setMasterVolume(
	Volume float32,
)

//go:wasmimport _raylib _GetMasterVolume
//go:noescape
func getMasterVolume(
	ret float32,
)

//go:wasmimport _raylib _LoadWave
//go:noescape
func loadWave(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadWaveFromMemory
//go:noescape
func loadWaveFromMemory(
	ret cptr,
	FileType cptr,
	FileData cptr,
	DataSize int32,
)

//go:wasmimport _raylib _IsWaveValid
//go:noescape
func isWaveValid(
	ret cptr,
	Wave cptr,
)

//go:wasmimport _raylib _LoadSound
//go:noescape
func loadSound(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadSoundFromWave
//go:noescape
func loadSoundFromWave(
	ret cptr,
	Wave cptr,
)

//go:wasmimport _raylib _LoadSoundAlias
//go:noescape
func loadSoundAlias(
	ret cptr,
	Source cptr,
)

//go:wasmimport _raylib _IsSoundValid
//go:noescape
func isSoundValid(
	ret cptr,
	Sound cptr,
)

//go:wasmimport _raylib _UpdateSound
//go:noescape
func updateSound(
	Sound cptr,
	Data cptr,
	SampleCount int32,
)

//go:wasmimport _raylib _UnloadWave
//go:noescape
func unloadWave(
	Wave cptr,
)

//go:wasmimport _raylib _UnloadSound
//go:noescape
func unloadSound(
	Sound cptr,
)

//go:wasmimport _raylib _UnloadSoundAlias
//go:noescape
func unloadSoundAlias(
	Alias cptr,
)

//go:wasmimport _raylib _ExportWave
//go:noescape
func exportWave(
	ret cptr,
	Wave cptr,
	FileName cptr,
)

//go:wasmimport _raylib _ExportWaveAsCode
//go:noescape
func exportWaveAsCode(
	ret cptr,
	Wave cptr,
	FileName cptr,
)

//go:wasmimport _raylib _PlaySound
//go:noescape
func playSound(
	Sound cptr,
)

//go:wasmimport _raylib _StopSound
//go:noescape
func stopSound(
	Sound cptr,
)

//go:wasmimport _raylib _PauseSound
//go:noescape
func pauseSound(
	Sound cptr,
)

//go:wasmimport _raylib _ResumeSound
//go:noescape
func resumeSound(
	Sound cptr,
)

//go:wasmimport _raylib _IsSoundPlaying
//go:noescape
func isSoundPlaying(
	ret cptr,
	Sound cptr,
)

//go:wasmimport _raylib _SetSoundVolume
//go:noescape
func setSoundVolume(
	Sound cptr,
	Volume float32,
)

//go:wasmimport _raylib _SetSoundPitch
//go:noescape
func setSoundPitch(
	Sound cptr,
	Pitch float32,
)

//go:wasmimport _raylib _SetSoundPan
//go:noescape
func setSoundPan(
	Sound cptr,
	Pan float32,
)

//go:wasmimport _raylib _WaveCopy
//go:noescape
func waveCopy(
	ret cptr,
	Wave cptr,
)

//go:wasmimport _raylib _WaveCrop
//go:noescape
func waveCrop(
	Wave cptr,
	InitFrame int32,
	FinalFrame int32,
)

//go:wasmimport _raylib _WaveFormat
//go:noescape
func waveFormat(
	Wave cptr,
	SampleRate int32,
	SampleSize int32,
	Channels int32,
)

//go:wasmimport _raylib _LoadWaveSamples
//go:noescape
func loadWaveSamples(
	ret cptr,
	Wave cptr,
)

//go:wasmimport _raylib _UnloadWaveSamples
//go:noescape
func unloadWaveSamples(
	Samples cptr,
)

//go:wasmimport _raylib _LoadMusicStream
//go:noescape
func loadMusicStream(
	ret cptr,
	FileName cptr,
)

//go:wasmimport _raylib _LoadMusicStreamFromMemory
//go:noescape
func loadMusicStreamFromMemory(
	ret cptr,
	FileType cptr,
	Data cptr,
	DataSize int32,
)

//go:wasmimport _raylib _IsMusicValid
//go:noescape
func isMusicValid(
	ret cptr,
	Music cptr,
)

//go:wasmimport _raylib _UnloadMusicStream
//go:noescape
func unloadMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _PlayMusicStream
//go:noescape
func playMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _IsMusicStreamPlaying
//go:noescape
func isMusicStreamPlaying(
	ret cptr,
	Music cptr,
)

//go:wasmimport _raylib _UpdateMusicStream
//go:noescape
func updateMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _StopMusicStream
//go:noescape
func stopMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _PauseMusicStream
//go:noescape
func pauseMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _ResumeMusicStream
//go:noescape
func resumeMusicStream(
	Music cptr,
)

//go:wasmimport _raylib _SeekMusicStream
//go:noescape
func seekMusicStream(
	Music cptr,
	Position float32,
)

//go:wasmimport _raylib _SetMusicVolume
//go:noescape
func setMusicVolume(
	Music cptr,
	Volume float32,
)

//go:wasmimport _raylib _SetMusicPitch
//go:noescape
func setMusicPitch(
	Music cptr,
	Pitch float32,
)

//go:wasmimport _raylib _SetMusicPan
//go:noescape
func setMusicPan(
	Music cptr,
	Pan float32,
)

//go:wasmimport _raylib _GetMusicTimeLength
//go:noescape
func getMusicTimeLength(
	ret float32,
	Music cptr,
)

//go:wasmimport _raylib _GetMusicTimePlayed
//go:noescape
func getMusicTimePlayed(
	ret float32,
	Music cptr,
)

//go:wasmimport _raylib _LoadAudioStream
//go:noescape
func loadAudioStream(
	ret cptr,
	SampleRate uint32,
	SampleSize uint32,
	Channels uint32,
)

//go:wasmimport _raylib _IsAudioStreamValid
//go:noescape
func isAudioStreamValid(
	ret cptr,
	Stream cptr,
)

//go:wasmimport _raylib _UnloadAudioStream
//go:noescape
func unloadAudioStream(
	Stream cptr,
)

//go:wasmimport _raylib _UpdateAudioStream
//go:noescape
func updateAudioStream(
	Stream cptr,
	Data cptr,
	FrameCount int32,
)

//go:wasmimport _raylib _IsAudioStreamProcessed
//go:noescape
func isAudioStreamProcessed(
	ret cptr,
	Stream cptr,
)

//go:wasmimport _raylib _PlayAudioStream
//go:noescape
func playAudioStream(
	Stream cptr,
)

//go:wasmimport _raylib _PauseAudioStream
//go:noescape
func pauseAudioStream(
	Stream cptr,
)

//go:wasmimport _raylib _ResumeAudioStream
//go:noescape
func resumeAudioStream(
	Stream cptr,
)

//go:wasmimport _raylib _IsAudioStreamPlaying
//go:noescape
func isAudioStreamPlaying(
	ret cptr,
	Stream cptr,
)

//go:wasmimport _raylib _StopAudioStream
//go:noescape
func stopAudioStream(
	Stream cptr,
)

//go:wasmimport _raylib _SetAudioStreamVolume
//go:noescape
func setAudioStreamVolume(
	Stream cptr,
	Volume float32,
)

//go:wasmimport _raylib _SetAudioStreamPitch
//go:noescape
func setAudioStreamPitch(
	Stream cptr,
	Pitch float32,
)

//go:wasmimport _raylib _SetAudioStreamPan
//go:noescape
func setAudioStreamPan(
	Stream cptr,
	Pan float32,
)

//go:wasmimport _raylib _SetAudioStreamBufferSizeDefault
//go:noescape
func setAudioStreamBufferSizeDefault(
	Size int32,
)

//go:wasmimport _raylib _SetAudioStreamCallback
//go:noescape
func setAudioStreamCallback(
	Stream cptr,
	Callback cptr,
)

//go:wasmimport _raylib _AttachAudioStreamProcessor
//go:noescape
func attachAudioStreamProcessor(
	Stream cptr,
	Processor cptr,
)

//go:wasmimport _raylib _DetachAudioStreamProcessor
//go:noescape
func detachAudioStreamProcessor(
	Stream cptr,
	Processor cptr,
)

//go:wasmimport _raylib _AttachAudioMixedProcessor
//go:noescape
func attachAudioMixedProcessor(
	Processor cptr,
)

//go:wasmimport _raylib _DetachAudioMixedProcessor
//go:noescape
func detachAudioMixedProcessor(
	Processor cptr,
)
